# fly.toml app configuration file generated for subscsense on 2023-05-16T00:21:44+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "subscsense"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
